name: Nix actions

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  west2nix-flake:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run checks
        run: nix flake check -L

  template-flake:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run checks
        run: nix flake check -L ./templates/application --override-input west2nix . --reference-lock-file ./flake.lock

  collect:
    runs-on: ubuntu-latest
    needs:
      - west2nix-flake
      - template-flake
    steps:
      - run: exit 0
